version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.3'
    container_name: dep_zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:3.2.3'
    container_name: dep_kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://127.0.0.1:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=test-topic:1:1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  grafana:
    image: 'grafana/grafana:8.0.3'
    container_name: dep_grafana
    ports:
      - '3000:3000'
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ../slack-kaldb-app:/var/lib/grafana/plugins
    environment:
      GF_LOG_MODE: "console file"
      GF_LOG_LEVEL: "info"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_PATHS_PLUGINS: "/var/lib/grafana/plugins"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "slack-kaldb-app,slack-kaldb-app-backend-datasource"

  s3:
    image: 'adobe/s3mock:2.1.29'
    container_name: dep_s3
    ports:
      - 9090:9090
    environment:
      - initialBuckets=test-s3-bucket

  openzipkin:
    image: 'openzipkin/zipkin-slim'
    container_name: dep_openzipkin
    ports:
      - 9411:9411

  #to build this image run 'docker build -t aubreyt/kaldb .'
  kaldb_preprocessor:
    image: 'aubreyt/kaldb'
    container_name: kaldb_preprocessor
    ports:
      - 8086:8086
    environment:
      # Node specific settings
      - NODE_ROLES=PREPROCESSOR
      - KALDB_PREPROCESSOR_USE_BULK_API=true
      - KALDB_PREPROCESSOR_SERVER_ADDRESS=kaldb_preprocessor
      # Shared settings
      - KALDB_ZK_CONNECTION_STRING=zookeeper:2181
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ZIPKIN_TRACING_ENDPOINT=http://openzipkin:9411/api/v2/spans
      - S3_ENDPOINT=http://dep_s3:9090
    depends_on:
      - zookeeper
      - kafka
      - s3
      - openzipkin

  kaldb_index:
    image: 'aubreyt/kaldb'
    container_name: kaldb_index
    ports:
      - 8080:8080
    environment:
      # Node specific settings
      - NODE_ROLES=INDEX
      - KALDB_INDEX_SERVER_ADDRESS=kaldb_index
      # Shared settings
      - KALDB_ZK_CONNECTION_STRING=zookeeper:2181
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ZIPKIN_TRACING_ENDPOINT=http://openzipkin:9411/api/v2/spans
      - S3_ENDPOINT=http://dep_s3:9090
    depends_on:
      - kaldb_preprocessor

  kaldb_manager:
    image: 'aubreyt/kaldb'
    container_name: kaldb_manager
    ports:
      - 8083:8083
    environment:
      # Node specific settings
      - NODE_ROLES=MANAGER
      - KALDB_MANAGER_SERVER_ADDRESS=kaldb_manager
      # Shared settings
      - KALDB_ZK_CONNECTION_STRING=zookeeper:2181
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ZIPKIN_TRACING_ENDPOINT=http://openzipkin:9411/api/v2/spans
      - S3_ENDPOINT=http://dep_s3:9090
    depends_on:
      - kaldb_preprocessor

  kaldb_query:
    image: 'aubreyt/kaldb'
    container_name: kaldb_query
    ports:
      - 8081:8081
    environment:
      # Node specific settings
      - NODE_ROLES=QUERY
      - KALDB_QUERY_SERVER_ADDRESS=kaldb_query
      - KALDB_MANAGER_CONNECTION_STRING=kaldb_manager:8083
      # Shared settings
      - KALDB_ZK_CONNECTION_STRING=zookeeper:2181
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ZIPKIN_TRACING_ENDPOINT=http://openzipkin:9411/api/v2/spans
      - S3_ENDPOINT=http://dep_s3:9090
    depends_on:
      - kaldb_preprocessor

  kaldb_cache:
    image: 'aubreyt/kaldb'
    container_name: kaldb_cache
    ports:
      - 8082:8082
    environment:
      # Node specific settings
      - NODE_ROLES=CACHE
      - KALDB_CACHE_SERVER_ADDRESS=kaldb_cache
      # Shared settings
      - KALDB_ZK_CONNECTION_STRING=zookeeper:2181
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ZIPKIN_TRACING_ENDPOINT=http://openzipkin:9411/api/v2/spans
      - S3_ENDPOINT=http://dep_s3:9090
    depends_on:
      - kaldb_preprocessor

  kaldb_recovery:
    image: 'aubreyt/kaldb'
    container_name: kaldb_recovery
    ports:
      - 8085:8085
    environment:
      # Node specific settings
      - NODE_ROLES=RECOVERY
      - KALDB_RECOVERY_SERVER_ADDRESS=kaldb_recovery
      # Shared settings
      - KALDB_ZK_CONNECTION_STRING=zookeeper:2181
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - ZIPKIN_TRACING_ENDPOINT=http://openzipkin:9411/api/v2/spans
      - S3_ENDPOINT=http://dep_s3:9090
    depends_on:
      - kaldb_preprocessor
