receivers:
  otlp:
    protocols:
      grpc:
      http:
  jaeger:
    protocols:
      grpc:
      thrift_http:
      thrift_compact:
      thrift_binary:
  zipkin:
    endpoint: "0.0.0.0:9411"  # Default Zipkin endpoint

exporters:
  opensearch:
    http:
      endpoint: "http://localhost:8086"
      #endpoint: "http://astra_preprocessor:8086"
      tls:
        insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 500
  attributes/airtrace:
    actions:
      - key: trace_id
        action: insert
        from_attribute: traceId
      - key: span_id
        action: insert
        from_attribute: spanId
  batch/airtrace:
    send_batch_max_size: 100
    send_batch_size: 100
    timeout: 10s

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof:
    endpoint: "0.0.0.0:1888"

service:
  extensions: [health_check, pprof]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [memory_limiter, attributes/airtrace, batch/airtrace]
      exporters: [opensearch]
#  telemetry:
#    logs:
#      level: "debug"