serverPort: 8080

indexerConfig:
  maxMessagesPerChunk: 100
  maxBytesPerChunk: 100000
  commitDurationSecs: 10
  refreshDurationSecs: 11
  staleDurationSecs: 7200
  dataTransformer: ${INDEXER_DATA_TRANSFORMER:-api_log}
  dataDirectory: "/tmp"

kafkaConfig:
  kafkaTopic: ${KAFKA_TOPIC:-test-topic}
  kafkaTopicPartition: ${KAFKA_TOPIC_PARTITION:-0}
  kafkaBootStrapServers: ${KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}
  kafkaClientGroup: ${KAFKA_CLIENT_GROUP:-kaldb-test}
  enableKafkaAutoCommit: "true"
  kafkaAutoCommitInterval: "5000"
  kafkaSessionTimeout: "30000"

s3Config:
  s3AccessKey: ${S3_ACCESS_KEY:-access}
  s3SecretKey: ${S3_SECRET_KEY:-key}
  s3Region: ${S3_REGION:-us-east-1}
  s3EndPoint: ${S3_ENDPOINT:-http://localhost:9090}
  s3Bucket: ${S3_BUCKET:-test-s3-bucket}

