name: Build and Push Docker Image CI

on:
  push:
    branches: [ "airbnb-main" ]
  workflow_dispatch: # This allows manual triggering of the workflow on any branch
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'airbnb-main'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image (for airbnb-main branch)
      if: github.ref_name == 'airbnb-main'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          airbnb/airtrace:latest
          airbnb/airtrace:${{ github.sha }}

    - name: Build and push Docker image (for non airbnb-main branch)
      if: github.ref_name != 'airbnb-main'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          airbnb/airtrace:${{ github.sha }}
